version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "HttpAppStack"
s3_bucket = "codeswiftr-take2"
s3_prefix = "HttpAppStack"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
