version: '3.8'
services:
  admin_backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - admin_db
         
  admin_queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - admin_db

  admin_db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: h4rdp4ssw0rd21
      MYSQL_ROOT_PASSWORD: r0oth4rd3rp45S
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
